FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    baresip \
    ffmpeg \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY config /config
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
